import {
  AlertSnapshotEntity,
  AuthProviderEntity,
  BrokerCredentialEntity,
  BrokerSessionEntity,
  BrokerTradingAccountDetailsEntity,
  BundlePlanEntity,
  CopyRelationshipEntity,
  MasterProfileEntity,
  MarketEntity,
  PlanEntity,
  PlanFeatureEntity,
  PlanLimitsEntity,
  PlanPricingEntity,
  PlanStrategyEntity,
  PlanTypeEntity,
  RazorpayOrderEntity,
  StrategyDetailsEntity,
  StrategyEntity,
  SubscriptionInvoiceEntity,
  SubscriptionPaymentEntity,
  TradeSignalEntity,
  UserBillingDetailsEntity,
  UserEntity,
  UserRefreshTokenEntity,
  UserSubscriptionEntity,
  UserTradingAccountDetailsEntity,
} from "./entities";

export * from "./entities";

export const ENTITIES = [
  UserEntity,
  UserRefreshTokenEntity,
  AuthProviderEntity,
  PlanTypeEntity,
  MarketEntity,
  PlanEntity,
  PlanFeatureEntity,
  PlanLimitsEntity,
  PlanPricingEntity,
  StrategyEntity,
  StrategyDetailsEntity,
  PlanStrategyEntity,
  BundlePlanEntity,
  UserSubscriptionEntity,
  SubscriptionInvoiceEntity,
  SubscriptionPaymentEntity,
  RazorpayOrderEntity,
  UserTradingAccountDetailsEntity,
  UserBillingDetailsEntity,
  MasterProfileEntity,
  CopyRelationshipEntity,
  BrokerCredentialEntity,
  BrokerSessionEntity,
  BrokerTradingAccountDetailsEntity,
  AlertSnapshotEntity,
  TradeSignalEntity,
];